name: graphql_web_socket_client
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.6.0

# Add regular dependencies here.
dependencies:
  graphql_web_socket_core:
    path: ../graphql_web_socket_core

  gql: ^1.0.0
  web_socket_channel: ^3.0.2
  uuid: ^4.5.1

  rxdart: ^0.28.0
  collection: ^1.19.0
  meta: ^1.15.0

dev_dependencies:
  test: ^1.25.8
  stream_channel: ^2.1.2

resolution: workspace
